version: "3"
services:
  source:
    build: ./customer-service-api
    ports:
      - "8080:8080"
    links:
      - "redis:redis"
      - "kafka:kafka"
  flow:
    build: ./tokenizer
    ports:
      - "8082"
    links:
      - "redis:redis"
      - "kafka:kafka"
  proof:
    build: ./consumer
    ports:
      - "8081"
    links:
      - "redis:redis"
      - "kafka:kafka"
  zookeeper:
    image: confluentinc/cp-zookeeper:4.1.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:4.1.1
    hostname: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PPS:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PPS://kafka:9092,INTERNAL://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PPS://kafka:9092,INTERNAL://kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"