version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:4.1.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:4.1.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PPS:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PPS://0.0.0.0:9092,INTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PPS://localhost:9092,INTERNAL://kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
  db:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"